##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [2.30.0] date: [Wed Nov 14 17:17:54 KST 2018] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = axio-builder-tpm


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES = \
Src/main.c \
Src/freertos.c \
Src/lwip.c \
Src/ethernetif.c \
Src/syscalls.c \
Src/mbedtls.c \
Src/net_sockets.c \
Src/hardware_rng.c \
Src/stm32f4xx_it.c \
Src/stm32f4xx_hal_msp.c \
Src/stm32f4xx_hal_timebase_TIM.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_eth.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cryp.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cryp_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hash.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hash_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rng.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_spi.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_hcd.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c \
Src/system_stm32f4xx.c \
Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c \
Middlewares/Third_Party/FreeRTOS/Source/list.c \
Middlewares/Third_Party/FreeRTOS/Source/event_groups.c \
Middlewares/Third_Party/FreeRTOS/Source/tasks.c \
Middlewares/Third_Party/FreeRTOS/Source/queue.c \
Middlewares/Third_Party/FreeRTOS/Source/croutine.c \
Middlewares/Third_Party/FreeRTOS/Source/timers.c \
Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/cmsis_os.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/auth.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/ccp.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/chap_ms.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/chap-md5.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/chap-new.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/demand.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/eap.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/eui64.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/fsm.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/ipcp.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/ipv6cp.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/lcp.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/magic.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/mppe.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/multilink.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/ppp.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/pppapi.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/pppcrypt.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/pppoe.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/pppol2tp.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/pppos.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/upap.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/utils.c \
Middlewares/Third_Party/LwIP/src/netif/ppp/vj.c \
Middlewares/Third_Party/LwIP/src/netif/ethernet.c \
Middlewares/Third_Party/LwIP/src/netif/slipif.c \
Middlewares/Third_Party/LwIP/src/netif/lowpan6.c \
Middlewares/Third_Party/LwIP/src/api/netdb.c \
Middlewares/Third_Party/LwIP/src/api/tcpip.c \
Middlewares/Third_Party/LwIP/src/api/api_lib.c \
Middlewares/Third_Party/LwIP/src/api/netbuf.c \
Middlewares/Third_Party/LwIP/src/api/api_msg.c \
Middlewares/Third_Party/LwIP/src/api/sockets.c \
Middlewares/Third_Party/LwIP/src/api/err.c \
Middlewares/Third_Party/LwIP/src/api/netifapi.c \
Middlewares/Third_Party/LwIP/src/core/mem.c \
Middlewares/Third_Party/LwIP/src/core/netif.c \
Middlewares/Third_Party/LwIP/src/core/def.c \
Middlewares/Third_Party/LwIP/src/core/stats.c \
Middlewares/Third_Party/LwIP/src/core/raw.c \
Middlewares/Third_Party/LwIP/src/core/sys.c \
Middlewares/Third_Party/LwIP/src/core/tcp_in.c \
Middlewares/Third_Party/LwIP/src/core/timeouts.c \
Middlewares/Third_Party/LwIP/src/core/inet_chksum.c \
Middlewares/Third_Party/LwIP/src/core/tcp.c \
Middlewares/Third_Party/LwIP/src/core/dns.c \
Middlewares/Third_Party/LwIP/src/core/tcp_out.c \
Middlewares/Third_Party/LwIP/src/core/memp.c \
Middlewares/Third_Party/LwIP/src/core/init.c \
Middlewares/Third_Party/LwIP/src/core/ip.c \
Middlewares/Third_Party/LwIP/src/core/pbuf.c \
Middlewares/Third_Party/LwIP/src/core/udp.c \
Middlewares/Third_Party/LwIP/src/core/ipv4/icmp.c \
Middlewares/Third_Party/LwIP/src/core/ipv4/ip4.c \
Middlewares/Third_Party/LwIP/src/core/ipv4/ip4_frag.c \
Middlewares/Third_Party/LwIP/src/core/ipv4/autoip.c \
Middlewares/Third_Party/LwIP/src/core/ipv4/ip4_addr.c \
Middlewares/Third_Party/LwIP/src/core/ipv4/dhcp.c \
Middlewares/Third_Party/LwIP/src/core/ipv4/igmp.c \
Middlewares/Third_Party/LwIP/src/core/ipv4/etharp.c \
Middlewares/Third_Party/LwIP/src/core/ipv6/inet6.c \
Middlewares/Third_Party/LwIP/src/core/ipv6/ethip6.c \
Middlewares/Third_Party/LwIP/src/core/ipv6/ip6_frag.c \
Middlewares/Third_Party/LwIP/src/core/ipv6/ip6.c \
Middlewares/Third_Party/LwIP/src/core/ipv6/nd6.c \
Middlewares/Third_Party/LwIP/src/core/ipv6/dhcp6.c \
Middlewares/Third_Party/LwIP/src/core/ipv6/mld6.c \
Middlewares/Third_Party/LwIP/src/core/ipv6/icmp6.c \
Middlewares/Third_Party/LwIP/src/core/ipv6/ip6_addr.c \
Middlewares/Third_Party/LwIP/system/OS/sys_arch.c \
Middlewares/Third_Party/LwIP/src/apps/mqtt/mqtt.c \
Middlewares/Third_Party/mbedTLS/library/aes.c \
Middlewares/Third_Party/mbedTLS/library/aesni.c \
Middlewares/Third_Party/mbedTLS/library/arc4.c \
Middlewares/Third_Party/mbedTLS/library/asn1parse.c \
Middlewares/Third_Party/mbedTLS/library/asn1write.c \
Middlewares/Third_Party/mbedTLS/library/base64.c \
Middlewares/Third_Party/mbedTLS/library/bignum.c \
Middlewares/Third_Party/mbedTLS/library/blowfish.c \
Middlewares/Third_Party/mbedTLS/library/camellia.c \
Middlewares/Third_Party/mbedTLS/library/ccm.c \
Middlewares/Third_Party/mbedTLS/library/certs.c \
Middlewares/Third_Party/mbedTLS/library/cipher.c \
Middlewares/Third_Party/mbedTLS/library/cipher_wrap.c \
Middlewares/Third_Party/mbedTLS/library/cmac.c \
Middlewares/Third_Party/mbedTLS/library/ctr_drbg.c \
Middlewares/Third_Party/mbedTLS/library/debug.c \
Middlewares/Third_Party/mbedTLS/library/des.c \
Middlewares/Third_Party/mbedTLS/library/dhm.c \
Middlewares/Third_Party/mbedTLS/library/ecdh.c \
Middlewares/Third_Party/mbedTLS/library/ecdsa.c \
Middlewares/Third_Party/mbedTLS/library/ecjpake.c \
Middlewares/Third_Party/mbedTLS/library/ecp.c \
Middlewares/Third_Party/mbedTLS/library/ecp_curves.c \
Middlewares/Third_Party/mbedTLS/library/entropy.c \
Middlewares/Third_Party/mbedTLS/library/entropy_poll.c \
Middlewares/Third_Party/mbedTLS/library/error.c \
Middlewares/Third_Party/mbedTLS/library/gcm.c \
Middlewares/Third_Party/mbedTLS/library/havege.c \
Middlewares/Third_Party/mbedTLS/library/hmac_drbg.c \
Middlewares/Third_Party/mbedTLS/library/md.c \
Middlewares/Third_Party/mbedTLS/library/md2.c \
Middlewares/Third_Party/mbedTLS/library/md4.c \
Middlewares/Third_Party/mbedTLS/library/md5.c \
Middlewares/Third_Party/mbedTLS/library/md_wrap.c \
Middlewares/Third_Party/mbedTLS/library/memory_buffer_alloc.c \
Middlewares/Third_Party/mbedTLS/library/oid.c \
Middlewares/Third_Party/mbedTLS/library/padlock.c \
Middlewares/Third_Party/mbedTLS/library/pem.c \
Middlewares/Third_Party/mbedTLS/library/pk.c \
Middlewares/Third_Party/mbedTLS/library/pkcs11.c \
Middlewares/Third_Party/mbedTLS/library/pkcs12.c \
Middlewares/Third_Party/mbedTLS/library/pkcs5.c \
Middlewares/Third_Party/mbedTLS/library/pkparse.c \
Middlewares/Third_Party/mbedTLS/library/pkwrite.c \
Middlewares/Third_Party/mbedTLS/library/pk_wrap.c \
Middlewares/Third_Party/mbedTLS/library/platform.c \
Middlewares/Third_Party/mbedTLS/library/ripemd160.c \
Middlewares/Third_Party/mbedTLS/library/rsa.c \
Middlewares/Third_Party/mbedTLS/library/sha1.c \
Middlewares/Third_Party/mbedTLS/library/sha256.c \
Middlewares/Third_Party/mbedTLS/library/sha512.c \
Middlewares/Third_Party/mbedTLS/library/ssl_cache.c \
Middlewares/Third_Party/mbedTLS/library/ssl_ciphersuites.c \
Middlewares/Third_Party/mbedTLS/library/ssl_cli.c \
Middlewares/Third_Party/mbedTLS/library/ssl_cookie.c \
Middlewares/Third_Party/mbedTLS/library/ssl_srv.c \
Middlewares/Third_Party/mbedTLS/library/ssl_ticket.c \
Middlewares/Third_Party/mbedTLS/library/ssl_tls.c \
Middlewares/Third_Party/mbedTLS/library/threading.c \
Middlewares/Third_Party/mbedTLS/library/timing.c \
Middlewares/Third_Party/mbedTLS/library/version.c \
Middlewares/Third_Party/mbedTLS/library/version_features.c \
Middlewares/Third_Party/mbedTLS/library/x509.c \
Middlewares/Third_Party/mbedTLS/library/x509write_crt.c \
Middlewares/Third_Party/mbedTLS/library/x509write_csr.c \
Middlewares/Third_Party/mbedTLS/library/x509_create.c \
Middlewares/Third_Party/mbedTLS/library/x509_crl.c \
Middlewares/Third_Party/mbedTLS/library/x509_crt.c \
Middlewares/Third_Party/mbedTLS/library/x509_csr.c \
Middlewares/Third_Party/mbedTLS/library/xtea.c

C_SOURCES += Drivers/TisTpmDrv/TisTpmDrv.c 

CPP_SOURCES = \
Src/RazorClam.cpp \
Src/TpmUtil.cpp \
Middlewares/CryptoAPI/CryptoApi.cpp \
Middlewares/Urchin/Platform/Platform.cpp \
Middlewares/Urchin/Lib/ActivateCredential.cpp \
Middlewares/Urchin/Lib/Certify.cpp \
Middlewares/Urchin/Lib/CertifyCreation.cpp \
Middlewares/Urchin/Lib/ChangeEPS.cpp \
Middlewares/Urchin/Lib/ChangePPS.cpp \
Middlewares/Urchin/Lib/ClearControl.cpp \
Middlewares/Urchin/Lib/Clear.cpp \
Middlewares/Urchin/Lib/ClockRateAdjust.cpp \
Middlewares/Urchin/Lib/ClockSet.cpp \
Middlewares/Urchin/Lib/CmdProcessor.cpp \
Middlewares/Urchin/Lib/CommandCodeAttributesTables.cpp \
Middlewares/Urchin/Lib/Commit.cpp \
Middlewares/Urchin/Lib/ContextLoad.cpp \
Middlewares/Urchin/Lib/ContextSave.cpp \
Middlewares/Urchin/Lib/CpriHash.cpp \
Middlewares/Urchin/Lib/CpriSym.cpp \
Middlewares/Urchin/Lib/Create.cpp \
Middlewares/Urchin/Lib/CreateLoaded.cpp \
Middlewares/Urchin/Lib/CreatePrimary.cpp \
Middlewares/Urchin/Lib/CryptUtil.cpp \
Middlewares/Urchin/Lib/DictionaryAttackLockReset.cpp \
Middlewares/Urchin/Lib/DictionaryAttackParameters.cpp \
Middlewares/Urchin/Lib/Duplicate.cpp \
Middlewares/Urchin/Lib/ECC_Parameters.cpp \
Middlewares/Urchin/Lib/ECDH_KeyGen.cpp \
Middlewares/Urchin/Lib/ECDH_ZGen.cpp \
Middlewares/Urchin/Lib/EC_Ephemeral.cpp \
Middlewares/Urchin/Lib/EncryptDecrypt2.cpp \
Middlewares/Urchin/Lib/EncryptDecrypt.cpp \
Middlewares/Urchin/Lib/EventSequenceComplete.cpp \
Middlewares/Urchin/Lib/EvictControl.cpp \
Middlewares/Urchin/Lib/FieldUpgradeData.cpp \
Middlewares/Urchin/Lib/FieldUpgradeStart.cpp \
Middlewares/Urchin/Lib/FirmwareRead.cpp \
Middlewares/Urchin/Lib/FlushContext.cpp \
Middlewares/Urchin/Lib/GetCapability.cpp \
Middlewares/Urchin/Lib/GetCommandAuditDigest.cpp \
Middlewares/Urchin/Lib/GetRandom.cpp \
Middlewares/Urchin/Lib/GetSessionAuditDigest.cpp \
Middlewares/Urchin/Lib/GetTestResult.cpp \
Middlewares/Urchin/Lib/GetTime.cpp \
Middlewares/Urchin/Lib/Hash.cpp \
Middlewares/Urchin/Lib/HashSequenceStart.cpp \
Middlewares/Urchin/Lib/HierarchyChangeAuth.cpp \
Middlewares/Urchin/Lib/HierarchyControl.cpp \
Middlewares/Urchin/Lib/HMAC.cpp \
Middlewares/Urchin/Lib/HMAC_Start.cpp \
Middlewares/Urchin/Lib/Import.cpp \
Middlewares/Urchin/Lib/IncrementalSelfTest.cpp \
Middlewares/Urchin/Lib/Load.cpp \
Middlewares/Urchin/Lib/LoadExternal.cpp \
Middlewares/Urchin/Lib/MakeCredential.cpp \
Middlewares/Urchin/Lib/Marshal.cpp \
Middlewares/Urchin/Lib/MemoryLib.cpp \
Middlewares/Urchin/Lib/NV_Certify.cpp \
Middlewares/Urchin/Lib/NV_ChangeAuth.cpp \
Middlewares/Urchin/Lib/NV_DefineSpace.cpp \
Middlewares/Urchin/Lib/NV_Extend.cpp \
Middlewares/Urchin/Lib/NV_GlobalWriteLock.cpp \
Middlewares/Urchin/Lib/NV_Increment.cpp \
Middlewares/Urchin/Lib/NV_Read.cpp \
Middlewares/Urchin/Lib/NV_ReadLock.cpp \
Middlewares/Urchin/Lib/NV_ReadPublic.cpp \
Middlewares/Urchin/Lib/NV_SetBits.cpp \
Middlewares/Urchin/Lib/NV_UndefineSpace.cpp \
Middlewares/Urchin/Lib/NV_UndefineSpaceSpecial.cpp \
Middlewares/Urchin/Lib/NV_Write.cpp \
Middlewares/Urchin/Lib/NV_WriteLock.cpp \
Middlewares/Urchin/Lib/ObjectChangeAuth.cpp \
Middlewares/Urchin/Lib/PCR_Allocate.cpp \
Middlewares/Urchin/Lib/PCR_Event.cpp \
Middlewares/Urchin/Lib/PCR_Extend.cpp \
Middlewares/Urchin/Lib/PCR_Read.cpp \
Middlewares/Urchin/Lib/PCR_Reset.cpp \
Middlewares/Urchin/Lib/PCR_SetAuthPolicy.cpp \
Middlewares/Urchin/Lib/PCR_SetAuthValue.cpp \
Middlewares/Urchin/Lib/PolicyAuthorize.cpp \
Middlewares/Urchin/Lib/PolicyAuthorizeNV.cpp \
Middlewares/Urchin/Lib/PolicyAuthValue.cpp \
Middlewares/Urchin/Lib/PolicyCommandCode.cpp \
Middlewares/Urchin/Lib/PolicyCounterTimer.cpp \
Middlewares/Urchin/Lib/PolicyCpHash.cpp \
Middlewares/Urchin/Lib/PolicyDuplicationSelect.cpp \
Middlewares/Urchin/Lib/PolicyGetDigest.cpp \
Middlewares/Urchin/Lib/PolicyLocality.cpp \
Middlewares/Urchin/Lib/PolicyNameHash.cpp \
Middlewares/Urchin/Lib/PolicyNV.cpp \
Middlewares/Urchin/Lib/PolicyNVWritten.cpp \
Middlewares/Urchin/Lib/PolicyOR.cpp \
Middlewares/Urchin/Lib/PolicyPassword.cpp \
Middlewares/Urchin/Lib/PolicyPCR.cpp \
Middlewares/Urchin/Lib/PolicyPhysicalPresence.cpp \
Middlewares/Urchin/Lib/PolicyRestart.cpp \
Middlewares/Urchin/Lib/PolicySecret.cpp \
Middlewares/Urchin/Lib/PolicySigned.cpp \
Middlewares/Urchin/Lib/PolicyTemplate.cpp \
Middlewares/Urchin/Lib/PolicyTicket.cpp \
Middlewares/Urchin/Lib/PP_Commands.cpp \
Middlewares/Urchin/Lib/Quote.cpp \
Middlewares/Urchin/Lib/ReadClock.cpp \
Middlewares/Urchin/Lib/ReadPublic.cpp \
Middlewares/Urchin/Lib/Rewrap.cpp \
Middlewares/Urchin/Lib/RSA_Decrypt.cpp \
Middlewares/Urchin/Lib/RSA_Encrypt.cpp \
Middlewares/Urchin/Lib/SelfTest.cpp \
Middlewares/Urchin/Lib/SequenceComplete.cpp \
Middlewares/Urchin/Lib/SequenceUpdate.cpp \
Middlewares/Urchin/Lib/SetAlgorithmSet.cpp \
Middlewares/Urchin/Lib/SetCommandCodeAuditStatus.cpp \
Middlewares/Urchin/Lib/SetPrimaryPolicy.cpp \
Middlewares/Urchin/Lib/Shutdown.cpp \
Middlewares/Urchin/Lib/Sign.cpp \
Middlewares/Urchin/Lib/StartAuthSession.cpp \
Middlewares/Urchin/Lib/Startup.cpp \
Middlewares/Urchin/Lib/stdafx.cpp \
Middlewares/Urchin/Lib/StirRandom.cpp \
Middlewares/Urchin/Lib/TestParms.cpp \
Middlewares/Urchin/Lib/Unseal.cpp \
Middlewares/Urchin/Lib/VerifySignature.cpp \
Middlewares/Urchin/Lib/ZGen_2Phase.cpp

# ASM sources
ASM_SOURCES =  \
startup_stm32f437xx.s


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
CPP = $(GCC_PATH)/$(PREFIX)g++
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
CPP = $(PREFIX)g++
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DMBEDTLS_CONFIG_FILE=\"mbedtls_config.h\" \
-DUSE_HAL_DRIVER \
-DSTM32F437xx

C_DEFS += -DTISSPI=1 -DTPMSPIBUSHANDLE=hspi2 -DTPMSPIBUSCSPORT=GPIOI -DTPMSPIBUSCSPIN=GPIO_PIN_0
C_DEFS += -DWOLFSSL_USER_SETTINGS


# AS includes
AS_INCLUDES =  \
-I/Inc

# C includes
C_INCLUDES =  \
-IInc \
-IMiddlewares/Third_Party/LwIP/src/include \
-IMiddlewares/Third_Party/LwIP/system \
-IMiddlewares/Third_Party/mbedTLS/include \
-IDrivers/STM32F4xx_HAL_Driver/Inc \
-IDrivers/STM32F4xx_HAL_Driver/Inc/Legacy \
-IMiddlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F \
-IMiddlewares/Third_Party/LwIP/src/include/netif/ppp \
-IDrivers/CMSIS/Device/ST/STM32F4xx/Include \
-IMiddlewares/Third_Party/FreeRTOS/Source/include \
-IMiddlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS \
-IMiddlewares/Third_Party/LwIP/src/include/lwip \
-IMiddlewares/Third_Party/LwIP/src/include/lwip/apps \
-IMiddlewares/Third_Party/LwIP/src/include/lwip/priv \
-IMiddlewares/Third_Party/LwIP/src/include/lwip/prot \
-IMiddlewares/Third_Party/LwIP/src/include/netif \
-IMiddlewares/Third_Party/LwIP/src/include/posix \
-IMiddlewares/Third_Party/LwIP/src/include/posix/sys \
-IMiddlewares/Third_Party/LwIP/system/arch \
-IMiddlewares/Third_Party/mbedTLS/include/mbedtls \
-IDrivers/CMSIS/Include

C_INCLUDES += -IDrivers/TisTpmDrv
C_INCLUDES += -IMiddlewares/Urchin/Inc
C_INCLUDES += -IMiddlewares/CryptoAPI

# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"

CPPFLAGS = $(CFLAGS)

#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F437IIHx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections
LDFLAGS += -Wl,--no-wchar-size-warning

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(CPP_SOURCES:.cpp=.o)))
vpath %.cpp $(sort $(dir $(CPP_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	@echo " CC $@"
	@$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.cpp Makefile | $(BUILD_DIR) 
	@echo " CPP $@"
	@$(CPP) -c $(CPPFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.cpp=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	@echo " AS $@"
	@$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	@echo " GEN $@"
	@$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
AXSIGN=./dist/axtool/linux_64bit/axsign
AXTOOL=./dist/axtool/linux_64bit/axtool
AXOPT=-t builder_stm32
AXTTY=/dev/ttyUSB0
PRIVPEM=dist/axtool/private.pem 

$(TARGET).bin.00000000.sig: $(BUILD_DIR)/$(TARGET).bin
	@$(AXSIGN) $(AXOPT) $< $(PRIVPEM) 0
flash: $(TARGET).bin.00000000.sig
	@$(AXTOOL) $(AXOPT) -f $< $(AXTTY)

.PHONY: flash

#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
